### ISSUE TITLE
Ratchet down CA lifetimes

### ISSUE THREAD

**Issue by nightkr** [stackabletech/secret-operator#358]
We used to hard-code CA durations to 2 years, because we didn't have a way to rotate them, and we didn't have a way to override it. These days both of these have been addressed (#93, #354), so there's no reason anymore to keep it as ridiculously long. As a starting point, a week should be more than plenty, but in that case we would also need to reduce the default `maxCertificateLifetime`.

/cc @sbernauer 
```[tasklist]
### Tasks
- [ ] https://github.com/stackabletech/secret-operator/pull/403
- [ ] https://github.com/stackabletech/secret-operator/pull/441
- [x] Blog Post (Optional)
```

**Comment by sbernauer** [comment]
Happy to reduce it to something less than 2 years, but would prefer >= 15 days or even >= 31 days. Let's have a discussion (in e.g. Arch meeting)

**Comment by lfrancke** [comment]
I made the decision to move it to 1 year for the 24.3 release together with release notes and maybe a blog post announcing our future plans of lowering this even further.

We need documentation on what it means and an FAQ or something similar on what it means

**Comment by lfrancke** [comment]
Refinement by Nick, Sascha

**Comment by NickLarsenNZ** [comment]
Does this require anything more than just setting the default CA lifetime?

**Comment by lfrancke** [comment]
Documentation and potentially a blog post outlining our policy going forward but that's optional.
And a follow-up issue.

But in general I had hoped that this is going to be a simple thing, yes.

**Comment by NickLarsenNZ** [comment]
@lfrancke, what kind of documentation do you mean? I assume you mean on the docs site. Just need to know at least one of the following:

1. Where in the navigation hierarchy?
2. To what extent does it need documenting?

I can probably figure it out from there.

**Comment by lfrancke** [comment]
It is still not very common to have short lifetimes for certificates and I think we should document it _somewhere_.
Not sure what the best place would be. @fhennig 

I don't think it needs much. Just a paragraph about our certificate handlind.

**Comment by fhennig** [comment]
The Secret operator could use a bit more docs in general. There isn't really a section about it being able to do TLS certs, there isn't a good landing page. Maybe I'd just stick it in the [Usage](https://docs.stackable.tech/home/stable/secret-operator/usage) page or the 'Security' page.

**Comment by NickLarsenNZ** [comment]
> The Secret operator could use a bit more docs in general. There isn't really a section about it being able to do TLS certs, there isn't a good landing page. Maybe I'd just stick it in the [Usage](https://docs.stackable.tech/home/stable/secret-operator/usage) page or the 'Security' page.

I have read both, and Usage seems most suitable. I'll update the task list in the description.

**Comment by sbernauer** [comment]
During planning it was decided to leave the lifetime at 1 year for now and create follow-up tickets as needed
